# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CSRT Linting and Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-lint-and-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update Github Actions Path
      run: |
        echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install --user pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pipenv run lint
    - name: Check dependencies for security issues
      run: |
        pipenv check -i 39252
    - name: Test with pytest
      run: |
        pipenv run test
    - name: Build docker image
      uses: docker/build-push-action@v2
